### ISSUE TITLE
Please allow installation with L5

### ISSUE THREAD

**Issue by twoSeats** [anlutro/laravel-settings#10]
Hi, please could you update composer.json to allow installation with Laravel 5

**Comment by anlutro** [comment]
The library should work with Laravel 5 now. The only caveat is that you have to manually call `Setting::save()` after modifying them - they won't save automatically.

**Comment by garygreen** [comment]
@anlutro you can use the php function `register_shutdown_function` which might be a suitable altnerative. If you want to do it the 'cool kids' way with Laravel 5 middleware, you can use `TerminableMiddleware` (session does this to store session at the end of the script)

**Comment by anlutro** [comment]
I will do the middleware, shutdown function is a big no no. I'm just lazy about it since I don't use version 5 myself.

**Comment by garygreen** [comment]
I'll try and implement it and do a PR. Out of interest what's your beef with the `register_shutdown_function`? ;-)

**Comment by anlutro** [comment]
Libraries should mess with PHP's lifecycle as little as possible unless it's something very specific like an error handler - it just makes problems so much harder to track down. What would happen if the save call inside `register_shutdown_function` threw an exception? I wouldn't know without testing it manually. What if it occurs after `fastcgi_finish_request()`?

PRs would be more than welcome! :)

**Comment by garygreen** [comment]
@anlutro this could probably be closed now pr #17 is merged

**Comment by anlutro** [comment]
Yep. Thanks!
