### ISSUE TITLE
Every setting is saved multiple times in every request

### ISSUE THREAD

**Issue by carlost89** [anlutro/laravel-settings#100]
Laravel version: 5.5.40
PHP version: 7.0

I added this code in a controller to save some settings in database:

`$key = $request->key;
        $value = $request->value;

        $setting->set($key, $value);

        $setting->setExtraColumns([
            'display_name' => $key,
            'type' => 'text',
        ]);

        $setting->save();

        return $setting->all();`

The problem is that when I save a new setting all the previous settings are resaved in database, making table growing so fast. Please someone tell me what I am doing wrong. Thank you.

**Comment by anlutro** [comment]
That's not the intended use of `setExtraColumns`. It's meant for things like a user ID if you want separate settings per user. Maybe the method name is not the best, and it can be made more clear in the documentation.

I'm also afraid there is no way to do what you want - saving a display name and type along with the value. It's an interesting feature request but might be difficult to implement. I would store the display names in translations, and types in the config.

**Comment by DePiedra** [comment]
Skip is possible for update. If the value is same then skip. I think its provide better performance.

in DatabaseSettingStore line 147
```
    protected function write(array $data)
    {
        $currentData = array_dot($this->read());
        $insertData = array_dot($data);
        $updateData = array();
        $deleteKeys = array();

        foreach ($currentData as $key => $value) {
            if (isset($insertData[$key])) {
                if ($insertData[$key] !== $value) {
                    $updateData[$key] = $insertData[$key];
                }
            } else {
                $deleteKeys[] = $key;
            }
            unset($insertData[$key]);
        }

        foreach ($updateData as $key => $value) {
            $this->newQuery()
                ->where($this->keyColumn, '=', $key)
                ->update(array($this->valueColumn => $value));
        }

        if ($insertData) {
            $this->newQuery(true)
                ->insert($this->prepareInsertData($insertData));
        }

        if ($deleteKeys) {
            $this->newQuery()
                ->whereIn($this->keyColumn, $deleteKeys)
                ->delete();
        }
    }

```

**Comment by aglipanci** [comment]
@anlutro I think the actual issue here is not the use of setExtraColumns but the issue which is also reported at #115 

Every time the save() method is called all the settings are re-updated on the DB.

I think there is a PR for this but is not merged yet.

**Comment by bweston92** [comment]
hopefully the PR https://github.com/anlutro/laravel-settings/pull/116 has fixed it, let me know if there is any issues

**Comment by aglipanci** [comment]
@bweston92 thanks for the quick reply. Unfortunately, now it saves nothing.

**Comment by bweston92** [comment]
Sorry @aglipanci reverted, I will take a look later.

**Comment by aglipanci** [comment]
@bweston92 did you had a chance to look at this?

**Comment by aglipanci** [comment]
@carlost89 my PR fixed this issue. Now it saves only if there is a change.
