### ISSUE TITLE
Settings are not saving into database

### ISSUE THREAD

**Issue by manojrhr** [anlutro/laravel-settings#102]
I have installed this repo to my laravel 5.6.12 and write this code
```
        setting()->set('foo', 'my value');
        setting()->save();
```
But my I didn't get anything in my settings table. Is there any thing I am missing?

**Comment by Venrir** [comment]
same for me

![image](https://i.mavis.moe/f/QkPMLyjZZC/2018-08-11-13-31-49gif.gif)

**Comment by bweston92** [comment]
@Venrir can you share how you've set it up, and the code that sets and saves?

**Comment by codevisiondevelopment** [comment]
config/settings.php
Change:
`'store' => 'json'`
To
`'store' => 'database'`

**Comment by larabar** [comment]
I'm having this same issue, the ::set() method does nothing, just returns null

::get() works perfectly fine, retrieving from the database as expected

**Comment by Hiros101** [comment]
Make sure to run `php artisan config:cache` after changing config file.

**Comment by sribna** [comment]
Still not working for Lara 8

`config/settings.php` exists, `'store' => 'database'`
_settings_ table also exists

Run `php artisan config:cache` several times

`ddd(setting()->set('test', 'value'))` returns NULL

`ddd(setting(['test' => 'value']))` returns a different result ( I 'd expect the same result)

```
anlutro\LaravelSettings\DatabaseSettingStore {#203 ▼
  #connection: Illuminate\Database\MySqlConnection {#200 ▶}
  #table: "settings"
  #keyColumn: "key"
  #valueColumn: "value"
  #queryConstraint: null
  #extraColumns: []
  #data: array:1 [▶]
  #updatedData: array:1 [▶]
  #persistedData: []
  #unsaved: true
  #loaded: true
  #defaults: array:1 [▶]
  #cache: null
  #cacheTtl: 15
  #cacheForgetOnWrite: true
}
```

**Comment by bweston92** [comment]
@sribna `setting()` called with an array will set the configuration and then return the result. When you call `set` on the store it will not. `set` is correct to be void.

`setting()`: https://github.com/anlutro/laravel-settings/blob/6029f6aeb84fe74cdfb0c0152e69576033fb665f/src/helpers.php#L8

`SettingStore::set()`: https://github.com/anlutro/laravel-settings/blob/6029f6aeb84fe74cdfb0c0152e69576033fb665f/src/SettingStore.php#L148
