### ISSUE TITLE
Enhancement - placeholder (%s, %d) replacement in settings

### ISSUE THREAD

**Issue by mr-jingles** [anlutro/laravel-settings#103]
Hi,
it would be nice -  to be able to send some variables with the key. So that placeholders in the value string will be replaced. For example:

'message' => setting('general.confirmation.mail_body',null,[auth()->user()->signature]). 
I'm currently using vsprintf in order to make this work. 

Thanks for this package!

**Comment by bweston92** [comment]
Changing the functionality of `settings` I think would be confusing.

I would be inclined to have a function named `settingf` and `set_settingf` instead.

**Comment by anlutro** [comment]
Hey, thanks for the suggestion!

I don't really think that PHP offers a nice way to provide this sort of functionality. Your example looks awkward with the `null` in the middle, for example. We could provide things like `format_setting` but then we should also provide things like `translate_setting`, and there are potentially multiple ways of formatting strings... I think it's best to just keep using `sprintf`.

**Comment by mr-jingles** [comment]
I am using a helper function - settingf - now. Thanks for the suggestion @bweston92!
