### ISSUE TITLE
Settings::fake() and Settings::assertSaved() for testing? 

### ISSUE THREAD

**Issue by jhm-ciberman** [anlutro/laravel-settings#104]
Hello. I have my app with a few settings. I want to test the route `admin.settings.update`:
I am currently using the json store.

```
    public function testSettingsUpdate() 
    {
        $user = factory(User::class)->create();

        // It should mock internally the "save" method
        Settings::fake(); 

        $this->actingAs($user)
            ->post(route('admin.settings.update'), [
                'collections' => [123, 456, 789] 
            ]))
            ->assertOk();

        // Should assert if the Settings::saved() was called
        Settings::assertSaved();
        $this->assertEquals(Settings::get('home.collections.0'), 123);
        $this->assertEquals(Settings::get('home.collections.1'), 456);
        $this->assertEquals(Settings::get('home.collections.2'), 789);
    }
```

Yes... this could be done with dependency injection. But... The spirit of Laravel is to test easily, do you think? 

So... It would be great to have those two methods:

```
Setting::fake();
Settings::assertSaved();
```

**Comment by bweston92** [comment]
Use the memory setting store. Touching the disk with the JSON store isn't desirable in tests anyway.

https://github.com/anlutro/laravel-settings/blob/master/src/MemorySettingStore.php

As for asserting the fact the data is saved is probably not ideal, this should middleware if I recall correct which saves anyway.

https://github.com/anlutro/laravel-settings/blob/master/src/SaveMiddleware.php

**Comment by anlutro** [comment]
Agreed with @bweston92 - the best mock is no mocking at all :)

There was an issue some time ago that Laravel 5.something didn't call the middleware's `terminate` method anymore so I'm not 100% sure if that's reliable anymore.

If you want to be sure that `save` has been called, maybe we should introduce a "buffer" in the memory store which means that `Settings::get` won't return the newly set value(s) before `save` has been called?

**Comment by bweston92** [comment]
A buffer or just  simple ‘hasChanges’ method?

**Comment by bweston92** [comment]
It would actually be very hard if bad people use mutable objects too.

If `set` is called with an object or array containing an object within, then mutation can occur without us knowing.

**Comment by jhm-ciberman** [comment]
> Use the memory setting store. Touching the disk with the JSON store isn't desirable in tests anyway.
> 
> https://github.com/anlutro/laravel-settings/blob/master/src/MemorySettingStore.php
> 
> As for asserting the fact the data is saved is probably not ideal, this should middleware if I recall correct which saves anyway.
> 
> https://github.com/anlutro/laravel-settings/blob/master/src/SaveMiddleware.php

Hello again. It seems fantastic. How do you recomend changing the Store driver? 

I changed the following lines in the config file:

```php
	/*
	|--------------------------------------------------------------------------
	| Default Settings Store
	|--------------------------------------------------------------------------
	|
	| This option controls the default settings store that gets used while
	| using this settings library.
	|
	| Supported: "json", "database", "array"
	|
	*/
	'store' => env('SETTINGS_DRIVER', 'json'),


```

And then I use the environment variable to change the store for the testing env. 

I think this should be documented on the readme and changed in the config file. 

I currently don't have the time, but I can make a PR later if you agree (or you can do it yourself so it's faster)

**Comment by anlutro** [comment]
Setting the environment variable in phpunit.xml seems like a perfectly fine approach, and is what is recommended by the Laravel docs.

**Comment by bweston92** [comment]
Looks like a solution was reached, will close feel free to reopen.
