### ISSUE TITLE
Saving and retrieving settings for different users

### ISSUE THREAD

**Issue by rehmatworks** [anlutro/laravel-settings#105]
Hello,
Your readme asks to add this:
```php
Setting::setExtraColumns(array(
	'user_id' => Auth::user()->id
));
```
But where do we need to add this? In `ServiceProvider.php`? Or where? Please help. Moreover, what's the easy way to get setting for a different user? `setting('my_key')` will retrieve the setting for the signed in user, but how can we retrieve the setting for a different user? Any explanation will be appreciated.

**Comment by anlutro** [comment]
In a service provider's `boot` method (if that is still a thing) is fine. In general it depends on what you want to set the extra columns for. And no, there's no easy way to get settings for a different user - I'd recommend just manually querying the database for that.

**Comment by leabdalla** [comment]
I've the same scenario and partially solved with `app/Providers/SettingServiceProvider.php`

    <?php

    namespace App\Providers;
    use Auth, JWTAuth;
    use Illuminate\Support\ServiceProvider;

    class SettingServiceProvider extends ServiceProvider
    {
        public function boot()
        {
            if(\Auth::guard('api')->check()){

                $user = JWTAuth::parseToken()->authenticate();
                \Setting::setConstraint(function($query, $insert) use ($user){
                    if ($insert) return;
                    $query->where('user_id', $user->id)->orWhere('user_id', NULL);
                });

            }else{

                \Setting::setExtraColumns(array('user_id' => NULL));

            }
        }
    }

This way I'm always filtering settings by API authenticated user when needed.
I tried to follow the same approach to check Web guard but for some strange reason it didn't worked, so I removed this logic and created a Helper to get directly in DB:

`App/Helpers/SettingHelper.php`

    <?php namespace App\Helpers;

    use DB, Auth, Setting, JWTAuth;

    class SettingHelper
    {

        public static function getUserSettings()
        {
            $q = DB::table('settings')->select('key', 'value');

            if(\Auth::guard('api')->check()){
                $user = JWTAuth::parseToken()->authenticate();
                $q->where('user_id', $user->id)->orWhere('user_id', NULL);
            }elseif(\Auth::guard('web')->check()){
                $user = \Auth::guard('web')->user();
                $q->where('user_id', $user->id)->orWhere('user_id', NULL);
            }

            $rs = $q->orderBy('user_id', 'asc')->get()->toArray();
            $arr = [];
            foreach($rs as $k => $v){
                $arr[$rs[$k]->key] = $rs[$k]->value;
            }

            return $arr;
        }

    }

Thats what I'm using now.
