### ISSUE TITLE
Override laravel configuration

### ISSUE THREAD

**Issue by kamov** [anlutro/laravel-settings#107]
I would like to override laravel configuration from the settings.

Something like below in config/app.php

```
'name' => env('APP_NAME', setting('app.name', 'Laravel')),
```

When I try I get blank page.

Where is best place to do this?

Thanks

**Comment by bweston92** [comment]
The issue here is `setting` is being called prior to it being setup.

**Comment by kamov** [comment]
I understand.. where is best place to put the override of config? in service provider?

**Comment by bweston92** [comment]
You can put it in a service provider yes.
