### ISSUE TITLE
Multiple json file

### ISSUE THREAD

**Issue by kamov** [anlutro/laravel-settings#109]
Can I use mutiple json file? If yes, how to store and retrieve from multiple json file?

Thanks

**Comment by bweston92** [comment]
This logic would have to sit in your own JSON store implementation there is to many different setups/layouts of files people may want to use for us to cater this.

**Comment by kamov** [comment]
I understand. I think that you could do something like Laravel config, where each file of config is begin of namespace of keys, like config('app.name'); where 'app' is the filename app.php

So for you would be setting('app.name') where 'app' is filename app.json

When you said to use my own json store implementation, I suppose you mean this:
https://github.com/anlutro/laravel-settings#custom-stores

In my custom store, I can use `Setting::setPath($path)` each time need to set or get from setting, or you think there is better way?

Thank You

**Comment by kamov** [comment]
If everything is stored in single file, by using settings in relation with a user_id, then the file can become very large. Or not?
