### ISSUE TITLE
Model for using with laravel auditing

### ISSUE THREAD

**Issue by zefexdeveloper** [anlutro/laravel-settings#112]
I'm using https://github.com/owen-it/laravel-auditing so I can keep track of what changes in my application and I was wondering, how can I set up in your package as I don't have access to the model?
I need to declare `use \OwenIt\Auditing\Auditable;` in the model.
It's REALLY important cause I might store information such price for products and things like that I want to keep track of what changes and who did.

**Comment by bweston92** [comment]
Given the little amount of changes we have done in the last few years I would recommend forking and maintaining your own copy with your features.

Closing, feel free to reopen.
