### ISSUE TITLE
Error: Array to string convertion

### ISSUE THREAD

**Issue by lptn** [anlutro/laravel-settings#114]
Caused by https://github.com/anlutro/laravel-settings/commit/64847e5e0eddd62aaa5b32166fe8ff776ae66252#diff-5f739c62a5526bb1126b48e57a807b63R48

Condition: $default  === null, $key is an array

**Comment by bweston92** [comment]
Should be fixed in `0.8.3` https://github.com/anlutro/laravel-settings/commit/851dd685b5659edc07a34df0a5415217a6595654

**Comment by bweston92** [comment]
Closing, please re-open if there is any issues.

**Comment by lptn** [comment]
@bweston92 
Thanks for the fix!

There is an option to support defaults for multiply keys (not tested):
```php
if ($default === NULL) {
    $default = Arr::get(Config::get('settings.defaults'), $key);
}
```
