### ISSUE TITLE
Resaved all if at least one is installed

### ISSUE THREAD

**Issue by rayderua** [anlutro/laravel-settings#115]
Hello. 
As i see, when i call Setting::get they loaded all settins from database
```select * from `settings```

If I call once Settings::set / Settings::forget etc (any changes in settings) all settins will resaved in database. For example if i have 200 settings key in database, and change 1 key, it's generate 200 updates query to database. This creates an extra useless load on the database.

code:
```
Setting::set('debug',TRUE);
Setting::save();
``` 
logs:
```
$ cat www.query-2019-07-16.log | grep settings | grep select | wc -l
2
$ cat www.query-2019-07-16.log | grep settings | grep -o '\[update settings set value = ? where key = ?\]'  | wc -l
205
```
I think you need to track only the changed keys, and only cause updates for them.

**Comment by rayderua** [comment]
I fixed this issue in my code, by adding 4 lines in code
```bash
$ diff SettingStore.php SettingStoreFix.php 
35c35,43
< 	/**
---
>     /**
>      * Updated settings
>      *
>      * @var array
>      */
>     protected $updated = [];
> 
> 
>     /**
46d53
< 
71a79
> 
77a86
>                 array_push($this->updated, $k);
80a90
>             array_push($this->updated, $key);
```
```bash
$ diff DatabaseSettingStore.php DatabaseSettingStoreFix.php 
173a174
> 		    if ( FALSE == in_array($key, $this->updated) ) { continue; }
```

**Comment by bweston92** [comment]
Hi @rayderua thanks for spotting, do you mind putting in a PR?

**Comment by rayderua** [comment]
update previous comment patch for 0.8.3
What is PR?
in any case, if that fixes issue, then I don't mind :)

**Comment by rayderua** [comment]
May be this issue is a duplicate for 
https://github.com/anlutro/laravel-settings/issues/100
