### ISSUE TITLE
Laravel 6.0 support

### ISSUE THREAD

**Issue by xKairu** [anlutro/laravel-settings#117]
Just had a quick test and it seems to work on 6.0, just needs the composer updated to allow installation.

**Comment by bweston92** [comment]
@xKairu would you mind sending a PR?

**Comment by SadeghPM** [comment]
> Just had a quick test and it seems to work on 6.0, just needs the composer updated to allow installation.

Its not true. due to [upgrade guide](https://laravel.com/docs/6.0/upgrade#helpers) all `str_` and `array_` helpers removed from framework.
In this package for example:  file `DatabaseSettingStore.php`  array helper used (`array_dot`).Therefor you cant add laravel 6 support by just changing laravel version in `composer.json` file!

**Comment by SadeghPM** [comment]
Quick solution: requiring `laravel/helpers` in `composer.json`

**Comment by xKairu** [comment]
Yeah I just noticed the db driver issue. Took a crack at it [here](https://github.com/xKairu/laravel-settings), but I was having issues with `ArrayUtil::set` throwing `UnexpectedValueException`.

If I have `'test' => 'test'` in the database, then try saving `'test.test' => 'test'`, it'll throw the exception. If I do the nested key first, then unnested, it'll overwrite the first one.

Maybe someone smarter than me can do it properly. Not sure if my 6.0 checks are ideal, or the phpunit version constraint, either.

**Comment by bweston92** [comment]
I have added a recommended fix for this, can you all try `dev-master` and see if it is working as expected? If so I will tag a release.

**Comment by ilirhushi** [comment]
@bweston92 I am using `dev-master` version and so far everything seems good, I will let you know if I notice any issues

**Comment by bweston92** [comment]
Ok @ilirhushi which backend provider was you using? Could you possibly test both so I can make a release?

**Comment by ilirhushi** [comment]
@bweston92 currently on my system I am using `SettingStore` and is working OK

**Comment by bweston92** [comment]
Is that the file store or database store?

**Comment by ilirhushi** [comment]
@bweston92 Database store

**Comment by SergeyMiracle** [comment]
Any update on Laravel 6.0 support?

**Comment by ilirhushi** [comment]
@SergeyMiracle use the `dev-master` until @bweston92 makes a new release

**Comment by bweston92** [comment]
@ilirhushi are you using dev-master without any issues? I can tag a new major release if everything is working ok.

**Comment by ilirhushi** [comment]
@bweston92 so far I have used `dev-master` version and everything is working just fine, so I think you can tag a release

**Comment by bweston92** [comment]
Tagged as v0.9

**Comment by aglipanci** [comment]
@bweston92 I think you can close this one too.

**Comment by dschiller** [comment]
Could someone get it running on Laravel 6.x ?

If I use `Setting::set('breadcrumbs', 'true');` in my Controller nothing happens on Database side.

I am using Laravel 6.15.1. I also tried to add `laravel/helpers`which didn't change or fix it.

**Comment by aglipanci** [comment]
@dschiller I think you need to call Setting::save() to persist the changes on the DB.

**Comment by dschiller** [comment]
@aglipanci Wow, thanks a lot! I believe this Behaviour changed. Before Laravel 6.x I was using 5.x and there I used the `.set` Method which worked.

**Comment by dschiller** [comment]
@aglipanci Sorry made a Mistake. I doesn't work. I tried `set`and `save` both doesn't work. I wonder that I don't get any Errors.

**Comment by dschiller** [comment]
How can I execute the Tests at `vendor\anlutro\l4-settings\tests` ?

**Comment by dschiller** [comment]
Found it: `vendor\bin\phpunit vendor\anlutro\l4-settings\tests`

**Comment by dschiller** [comment]
Tests running succesfully:

```
λ vendor\bin\phpunit vendor\anlutro\l4-settings\tests
PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

.......................................................           55 / 55 (100%)

Time: 165 ms, Memory: 12.00 MB

OK (55 tests, 93 assertions)
```

**Comment by dschiller** [comment]
Fortunately `Setting::get()` works well.

**Comment by dschiller** [comment]
I tried

```
use anlutro\LaravelSettings\Facade as Setting;
...
Setting::save('breadcrumbs', 'false');
```

and also

```
use anlutro\LaravelSettings\SettingStore as Setting;
...
\Setting::set('breadcrumbs', 'false');
```

**Comment by dschiller** [comment]
Found a Solution:

```
setting();
setting(['breadcrumbs' => 'true'])->save();
```

This works for me. I have no idea why the other Code fails.
