### ISSUE TITLE
Publish config file fails

### ISSUE THREAD

**Issue by tlorentzen** [anlutro/laravel-settings#12]
Im getting the following error when running the config publish command.

php artisan config:publish anlutro/l4-settings

exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Config\Repository::package()' in /Users/Thomas/Documents/OAD/Projects/Project/vendor/anlutro/l4-settings/src/ServiceProvider.php:57
Stack trace:
#0 /Users/Thomas/Documents/OAD/Projects/Project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}

**Comment by anlutro** [comment]
Which Laravel version are you on?

**Comment by tlorentzen** [comment]
Laravel 5.0 stable

**Comment by anlutro** [comment]
I'll look at it. I guess v5 support should still be considered experimental. I don't have any apps I intend to update to v5 yet so sorry for the lag on fixing issues.

**Comment by tlorentzen** [comment]
Okay
I will see if i can come up with a fix.

**Comment by anlutro** [comment]
Try changing the version of my package to `dev-master@dev` in your composer.json and see if it works now.

**Comment by tlorentzen** [comment]
Hi, it looks like it working now :+1: I will do some testing tomorrow and write back.

It also looks like you have to update the documentation, i can see that other packages are publishing config files in Laravel 5 with the following command:

php artisan vendor:publish

**Comment by tlorentzen** [comment]
1 suggestion is maybe moving the config file to the root of the config folder, can see intervention/image is doing that.

**Comment by anlutro** [comment]
Yeah I'll have a look at the readme.

I'd like to move the config file, it looks ugly the way it is now, but it doesn't look like I can without breaking backwards compatibility.

**Comment by anlutro** [comment]
Also keep in mind that you have to call `Setting::save()` manually since the shutdown callback that made it possible to auto-save is nonexistant in Laravel 5.

**Comment by tlorentzen** [comment]
So i did some testing, and it looks like it fails to locate the published config file.
No error is outputted, but nothing happens when changing 'store' to database, but if i change it directly in the package, it works.

So far that´s the only error i found.

**Comment by tlorentzen** [comment]
The mergeConfigFrom could be called from the Register method in the ServiceProvider.php
http://laravel.com/docs/5.0/packages#configuration

**Comment by anlutro** [comment]
Looks like having a folder for config files is impossible. At least I can't figure out a way. I've changed it to just publish a `config/settings.php` file now, that seems to work. Hopefully it doesn't overlap with any other packages...

**Comment by anlutro** [comment]
Assuming this works now. Let me know if it doesn't and I'll re-open.
