### ISSUE TITLE
DB Store Forget

### ISSUE THREAD

**Issue by englishpigdog** [anlutro/laravel-settings#13]
Hi Andreas

I'm using the db store method and I'm not able to get the 'forget' method to work. I've looked the source and I think the items that are forgotten are just removed from the array, so when the database queries are run there is nothing to remove any existing reference of that key in the database.

**Comment by anlutro** [comment]
Hey,

Can you change your version in composer.json to `dev-master@dev`, run `composer update anlutro/l4-settings` and see if the problem is fixed for you?

If it works I'll tag a version, the `dev-master` thing should only be temporary.

**Comment by englishpigdog** [comment]
Seems to be an issue in dev-master too unfortunately.

**Comment by anlutro** [comment]
OK, I think I nailed it in 3d4e89b. Try again please (make sure you get that exact commit when you `composer update` - it can be a bit delayed sometimes).

**Comment by englishpigdog** [comment]
Just tested it and it seems to be working. Nice work.

**Comment by anlutro** [comment]
Great. Tagged 0.2.13, so you can switch back to `0.2.*` for your version constraint.
