### ISSUE TITLE
Illuminate\Contracts\Container\BindingResolutionException thrown with message "Target [anlutro\LaravelSettings\SettingStore] is not instantiable while building [anlutro\LaravelSettings\SaveMiddleware]."

### ISSUE THREAD

**Issue by engeslamsaad** [anlutro/laravel-settings#139]
Illuminate\Contracts\Container\BindingResolutionException thrown with message "Target [anlutro\LaravelSettings\SettingStore] is not instantiable while building [anlutro\LaravelSettings\SaveMiddleware]."

Stacktrace:
#13 Illuminate\Contracts\Container\BindingResolutionException in /var/www/html/ecommerce-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:960
#12 Illuminate\Container\Container:notInstantiable in /var/www/html/ecommerce-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:794
#11 Illuminate\Container\Container:build in /var/www/html/ecommerce-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:667
#10 Illuminate\Container\Container:resolve in /var/www/html/ecommerce-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:615
#9 Illuminate\Container\Container:make in /var/www/html/ecommerce-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:767
#8 Illuminate\Foundation\Application:make in /var/www/html/ecommerce-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:927
#7 Illuminate\Container\Container:resolveClass in /var/www/html/ecommerce-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:855
#6 Illuminate\Container\Container:resolveDependencies in /var/www/html/ecommerce-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:816
#5 Illuminate\Container\Container:build in /var/www/html/ecommerce-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:667
#4 Illuminate\Container\Container:resolve in /var/www/html/ecommerce-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:615
#3 Illuminate\Container\Container:make in /var/www/html/ecommerce-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:767
#2 Illuminate\Foundation\Application:make in /var/www/html/ecommerce-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:215
#1 Illuminate\Foundation\Http\Kernel:terminateMiddleware in /var/www/html/ecommerce-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:189
#0 Illuminate\Foundation\Http\Kernel:terminate in /var/www/html/ecommerce-laravel/public/index.php:62

**Comment by anlutro** [comment]
Did you run `php artisan config:publish` as described [here](https://github.com/anlutro/laravel-settings#installation---laravel--55)?
