### ISSUE TITLE
Documentation on the different stores

### ISSUE THREAD

**Issue by JessNielsen** [anlutro/laravel-settings#14]
Hi, could you perhaps add a bit more documentation on how to use the JSON store and the databse store, i guess that its something you change in the config, but an actual example would be nice

**Comment by anlutro** [comment]
Yeah I can work on that. If you publish the config file as described in the readme and edit the published file, you can change various settings there, including which store to use.

**Comment by JessNielsen** [comment]
also, do i have to run the createJsonDriver() before using the package?

**Comment by anlutro** [comment]
No, that's done for you. You can just do `Setting::get('foo')` or whatever and the appropriate driver will be created automatically.

**Comment by JessNielsen** [comment]
Ok thanks!
