### ISSUE TITLE
got "syntax error, unexpected ')' when using 0.11.1

### ISSUE THREAD

**Issue by tgarm** [anlutro/laravel-settings#142]
When using 0.11.1, calling "Setting::all();", got the error message:
![1589353930](https://user-images.githubusercontent.com/24644183/81782288-2e883700-952c-11ea-9d15-60aaae75e30f.jpg)

This can be solved by remove the "," in line 71.

**Comment by bweston92** [comment]
Thanks for the report, will add a fix in now.

**Comment by bweston92** [comment]
Released in `v0.11.2`
