### ISSUE TITLE
Returning an array of settings.

### ISSUE THREAD

**Issue by enkota** [anlutro/laravel-settings#143]
Hey,

I am trying to reduce the number of queries made by returning specific settings. An issue I've found is when returning an array where one of the values should return the default, it returns `null`.

Is there a way so that if `test` wasn't in the database yet, it can return the default value in a get array? I guess I could seed the database, but kind of makes the default values in config useless.

Thanks!

```
Setting::get(['foo', 'test']);
```

```
 'defaults' => [
	'foo' => 'bar',
	'test' => 'testvalue'
 ]
```

```
array:3 [▼
  "foo" => "bar"
  "test" => null
]
```

**Comment by anlutro** [comment]
Hey, thanks for opening the issue! This is definitely a bug, I'll make sure to look into it.

**Comment by enkota** [comment]
Awesome thanks @anlutro - For the time being I see you are returning all rows with a `get()` request regardless, so I'm just using multiple `get()` for each value. 

Brilliant package! Saves me building it out manually 👍

**Comment by anlutro** [comment]
Tagged v0.11.3 with a fix just now.

**Comment by enkota** [comment]
Brilliant thanks @anlutro ! Will give it a try.
