### ISSUE TITLE
Does it support Laravel 8?

### ISSUE THREAD

**Issue by ishan501** [anlutro/laravel-settings#152]
I'm getting the error: Class 'App\Http\Controllers\Setting' not found

I've added this line to app.php alias array: 'Setting' => 'anlutro\LaravelSettings\Facade',

Is it the correct way? Does it support V8?

**Comment by anlutro** [comment]
Hello! This has nothing to do with your Laravel version, just how PHP namespaces work. See https://github.com/anlutro/laravel-settings/issues/38
