### ISSUE TITLE
Extend get ?

### ISSUE THREAD

**Issue by ivanmijatovic89** [anlutro/laravel-settings#16]
i make table columns just like in your readme: key, value, user_id 
Can you please write me code for :
1. How can i get all  results where user_id = 1 ?
2. How can i get all results where user_id = 1 and key = 'site'?
Thanks

**Comment by anlutro** [comment]
Check the first example here: https://github.com/anlutro/laravel-settings/blob/master/README.md#database

Just replace `Auth::user()->id` with `1`, and then call `Setting::all()` or `Setting::get('site')`.

**Comment by ivanmijatovic89** [comment]
Thanks,
One more question.
How can i first get all settings where user_id = 1, and after that get all settings for user_id = 2? 
$user1_settings = ....;
$user2_settings = ....;
When i try to get two different settings ( with different query ) i always get back with same results
I use this code below, but i can't get it work
// User 1
Setting::setConstraint(function($query) {
	return $query->where('user_id','=',1);
});
$all = Setting::all();

// User 2	
Setting::setConstraint(function($query) {
    return $query->where('user_id','=',2);
});
$user2 = Setting::all();

**Comment by anlutro** [comment]
That's because query results are cached. I'll add some code that clears the cache when the constraint is changed, but honestly if you want to do this sort of thing you may as well just do it manually with `DB::table('settings')->all()` or whatever the name of your table is.

**Comment by ivanmijatovic89** [comment]
Thanks Anlutro,
In meantime i create my own settings storage. I can suggest that you are missing:
- easier way for querying data
- easier way for storing data ( example more columns )
Best regards

**Comment by anlutro** [comment]
Probably a good idea. I don't use the database store myself and probably never will, so I probably won't ever get around to implementing these more advanced features.
