### ISSUE TITLE
Can anlutro/l4-settings work with MongoDB ?

### ISSUE THREAD

**Issue by sergeynilov** [anlutro/laravel-settings#162]
In laravel 9 with MongoDB(jenssegers/mongodb 3.9) I added "anlutro/l4-settings": "^1.1"
and in file config/settings.php I set connection option:

```
    'connection' => 'mongodb',
	// Name of the table used.
	'table' => 'settings',

```	
In config/database.php file I have :
```
        'mongodb' => [
            'driver' => 'mongodb',
            ...
        ],
	
```
	
But calling method in control :
	
```
use anlutro\LaravelSettings\Facade as Setting;
...

        $backendItemsPerPage = Setting::get('backend_per_page', 123);
        \Log::info(varDump($backendItemsPerPage, ' -1 $backendItemsPerPage::'));

```
I got default "123"	 value, but not value from database.

Working with jenssegers/mongodb  in my models I have to replace  model declaration with 
use Jenssegers\Mongodb\Eloquent\Model;

Thanks!

**Comment by bweston92** [comment]
We don't currently have any plans to support any other database backends.

However you can create a setting store within your project that interacts with MongoDB.

An example of our database setting store https://github.com/anlutro/laravel-settings/blob/master/src/DatabaseSettingStore.php
