### ISSUE TITLE
Support arrays in ::get

### ISSUE THREAD

**Issue by garygreen** [anlutro/laravel-settings#18]
It would be cool to be able to get multiple settings like:

```php
$settings = Setting::get(['finance.vat_rate', 'app_name']);
```

Return:

```
[
    'finance' => [
        'vat_rate' => 20,
    ],
    'app_name' => 'My App'
]
```

**Comment by anlutro** [comment]
If this should be supported, I feel that the following should also work:

```php
Setting::get(['finance' => ['vat_rate'], 'app_name']);
```

What do you think?

**Comment by bweston92** [comment]
How would default value be handled in this scenario?

**Comment by anlutro** [comment]
That's a good question. I think non-existant array keys should be left out of the return value, unless you provide an array as the `$default` argument to `get()`, in which case that'll be merged with the result.

**Comment by bweston92** [comment]
Maybe make this another method `getMulti`?

**Comment by garygreen** [comment]
@anlutro possibly, I personally wouldn't use it, as I think when accessing properties you should only do so in dot-format. Laravel's `Config::` works same way, you can't send it a multi dimensl array to get, only dot format.

For default value, to keep things simple I would just return whatever you've set for any keys that it couldn't find. In theory you could add support for an array for `$default` but again probably overcomplicating it at this stage.

As an initial implementation, it could just support dot-format and returning single default value. Just a basic loop. This is how I've implemented something similar in my app (using the Laravel-5 style helper)

```php
/**
 * Get app setting
 * @param  string|array|null $name
 * @param  mixed $default
 * @return mixed
 */
function setting($name = null, $default = null)
{
	$setting = app('anlutro\LaravelSettings\SettingStore');
	
	if (is_null($name))
	{
		return $setting;
	}
	elseif (is_array($name))
	{
		$value = [];
		foreach ($name as $key)
		{
			$value[$key] = $setting->get($key, $default);
		}
	}
	else
	{
		$value = $setting->get($name, $default);
	}

	return $value;
}
```

**Comment by garygreen** [comment]
I wouldn't want an extra method like `getMulti` just for accessing by array. `get` should be fine and it keeps things consistent with multi array support similar to it's `set` sibling.

**Comment by anlutro** [comment]
Keeping it consistent with `Config::get` sounds good. Makes it easier to implement as well.

**Comment by anlutro** [comment]
Implemented here https://github.com/anlutro/laravel-settings/issues/19 in case you have any feedback.

**Comment by anlutro** [comment]
Added in 0.2.15
