### ISSUE TITLE
Creation of dynamic property anlutro\LaravelSettings\SaveMiddleware::$settings is deprecated

### ISSUE THREAD

**Issue by georgearnall** [anlutro/laravel-settings#184]
Started getting the following warnings in the logger. 

> Creation of dynamic property anlutro\LaravelSettings\SaveMiddleware::$settings is deprecated in /vendor/anlutro/l4-settings/src/SaveMiddleware.php on line 33

PHP Version: 8.3
Laravel Settings Version: 1.4.0

**Comment by anlutro** [comment]
thanks for reporting! I'll release this in 1.4.1 :)
