### ISSUE TITLE
Where to call setExtraColumns

### ISSUE THREAD

**Issue by MeeDNite** [anlutro/laravel-settings#20]
Hi,
Where should we call setExtraColumns and and custom Columns?

**Comment by anlutro** [comment]
Somewhere that's called before the request is routed. In 4.x that's either `app/start/global.php` or in a service provider's `boot()` method. In 5.x I suppose you have to write a middleware.

**Comment by kamaroly** [comment]
I tried it i the boot() but it's not working !

**Comment by anlutro** [comment]
Are you sure you're not calling `Setting::get` or something before you're calling `setExtraColums`?

Are you sure the service provider is actually loaded? Put a `die('test')` at the top of the `boot()` method.

**Comment by kamaroly** [comment]
@anlutro , thanks  I fixed it, I was passing a null object without knowing. What I have done I creaeted settings service provider and placed \Setting::setExtraColumns(array(
		   		 'user_id' => \Session::get('userId');
				));
init

**Comment by ConquestMedia** [comment]
@kamaroly doing this, but fell in #50 
please suggest
