### ISSUE TITLE
Need a builtin function for Setting::clear(), Setting::flush() or Setting::forgetAll()?

### ISSUE THREAD

**Issue by ZzAntares** [anlutro/laravel-settings#21]
Hello! Thanks for this very nice package! I've tried others before non have been perfect, but this one it's really really close, I think it only needs a way to flush, clear or remove all saved settings. Right now I've made a function to loop over all settings and forget them one by one, but could be nice to have this function builtin.

Or maybe this already exists but is not in the docs. Searching in the source I haven't found it either.

Thanks!

**Comment by anlutro** [comment]
You're right, it doesn't currently exist. I don't see a reason not to add it.

**Comment by anlutro** [comment]
Added in 0.3.0, which should be backwards compatible but has a few behaviour improvements.
