### ISSUE TITLE
Add a MemorySettingStore

### ISSUE THREAD

**Issue by rtconner** [anlutro/laravel-settings#23]
Store settings in memory only, and don't write them to anywhere permanent. 

The use case for this is for Unit Tests. Can't be writing to a json file every time I run Unit Tests.

**Comment by bweston92** [comment]
Would this be better called ArraySettingStore?



—

**Comment by anlutro** [comment]
Good idea.

I think "array" would be more consistent with Laravel, but "memory" is definitely the correct word to use.

**Comment by anlutro** [comment]
Added in 0.4, no breaking changes.

**Comment by rtconner** [comment]
Thanks so much for the fast response! This works great from my tests.
