### ISSUE TITLE
nested.element usage

### ISSUE THREAD

**Issue by illuminate3** [anlutro/laravel-settings#25]
Hi,

I was wondering how would I go about using "nested.element".

Thanks

**Comment by anlutro** [comment]
Should work out of the box. `Setting::get('foo.bar')`

**Comment by illuminate3** [comment]
I just playing with your package today so I'm still trying to get my way around it.
Thanks for saving me lots of time!

Sorry, I meant, how would I go saving to it? Do, I also need to make an extra column in the DB?

**Comment by anlutro** [comment]
`Setting::set('foo.bar', $value)` or `Setting::set('foo', ['bar' => $value]')`

Works just like `Config::get/set` or `array_get/array_set`.

You don't need any extra columns than `key` and `value`. Follow readme instructions and you should be fine.

**Comment by illuminate3** [comment]
Thanks!

I'm trying to figure out how to make some of the "settings" multi-lingual and I thought that the nested element would be a solution.

(I'm using github/vinkla/translator and all of this work is going towards github/illuminate3/rakko)

**Comment by anlutro** [comment]
If you only want certain settings to vary from language to language, nested elements is probably the best way.

If you want entirely different sets of settings for each language, you can use `Setting::setExtraColumns(['lang' => App::getLocale()])` if you're using the database store, or `Setting::setPath(storage_path(App::getLocale().'-settings.json'))` if you're using JSON.

**Comment by illuminate3** [comment]
Thanks!

I was wondering about the "setExtraColumns" feature. Is this db schemas or do I need to use it every time that I call "Setting::" ?

**Comment by anlutro** [comment]
See https://github.com/anlutro/laravel-settings/issues/20

**Comment by illuminate3** [comment]
Excellent!
Thanks!
