### ISSUE TITLE
Settings not saved on command.

### ISSUE THREAD

**Issue by martinmarianetti** [anlutro/laravel-settings#26]
Hi,

I'm using this package in a Command, I need to read/update the settings everytime it runs.
I can read it just fine, but when I need to update the current setting it does nothing.

I'm using Laravel 5, the field I need to update is a date string with 'Y-m-d H:i:s' format.

If I use it in my controllers it works fine, it fails only in a custom command.

**Comment by martinmarianetti** [comment]
You have to use Settings:save() in order to work.

**Comment by anlutro** [comment]
Hmm, that makes sense, as the middleware which does the auto-saving is only executed in a HTTP context. A bit of a regression from version 4's shutdown callbacks...

Like you said, you'll need to call `Setting::save()` manually when you're done operating on the settings. I'll add a note about this in the readme.

**Comment by martinmarianetti** [comment]
Great, thanks!

**Comment by anlutro** [comment]
Leaving issue open until I've done it, so I don't forget :)
