### ISSUE TITLE
Composer Update Issue

### ISSUE THREAD

**Issue by syscoavendano** [anlutro/laravel-settings#30]
Hi,

I have an issue with composer update and the error is

> php artisan clear-compiled
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'anlutro\\cURL\\Laravel\\cURLServiceProvider' not found","fil
e":"C:\\wamp\\www\\xxxxxx\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\ProviderRepository.php","line":158}}Script php artis
an clear-compiled handling the post-update-cmd event returned with an error

What should I do with this error.

by the way. im using Laravel 4.2.17

Thanks!

**Comment by anlutro** [comment]
This is a general Laravel error. Here's the simplest way to get around it.

1. Remove the service provider from your config/app.php.
2. Run `composer update`.
3. Put the service provider back into config/app.php.

If you want to avoid these sorts of problems in the long run, remove the "scripts" part of your composer.json and run a custom deployment script when needed, like in [this example](https://gist.github.com/anlutro/9523474).

**Comment by bweston92** [comment]
There is a "--no-scripts" option or something like that.



—
