### ISSUE TITLE
Fetching twice for another user

### ISSUE THREAD

**Issue by kendepelchin** [anlutro/laravel-settings#32]
Hey,
I want to fetch settings for a user after the initial fetch is done for the current logged in user (in a route middleware). I have an email that has to be translated to the locale of the user which will receive it.

In the repo $this->loaded is set to true when the initial fetch is done, so the second time it skips this and returns the data.
Any hints or tips on how to conquer this problem?

**Comment by anlutro** [comment]
A way to run a single settings get/set with a custom constraint would probably be a good feature.

For now, I suggest you either just write some custom code to do it, or use `Setting::setConstraint` or `Setting::setPath` appropriately to make the setting store get that user's settings that way.

**Comment by arcanedev-maroc** [comment]
I think it's better to reset the `loaded` property to `false` when the `setExtraColumns` is called.

**Comment by bweston92** [comment]
Closing as stale.
