### ISSUE TITLE
Migration Error on L4

### ISSUE THREAD

**Issue by Ejimba** [anlutro/laravel-settings#33]
Hi,

Great package. Thanks.

I am unable to run the database migration. Throws an error at about here:

https://github.com/anlutro/laravel-settings/blob/e38fd914e2c66215fda07db38ffe01e2cc5bcabf/src/migrations/2015_08_25_172600_create_settings_table.php#L10

"message":"Call to undefined function config()"

I did a dirty little hack to bypass it. Very, very, very dirty I might add. Directly in the vendor files! Please check it out. Or maybe its just my box. I don't know. (Laravel 4.2, Package version: 0.4.2)

**Comment by anlutro** [comment]
I see the problem and I'll get this fixed, but regardless I recommend you copy the migration from the package into `app/database/migrations` and manage it yourself there.

**Comment by Ejimba** [comment]
Awesome! Thanks
