### ISSUE TITLE
Class 'CreateSettingsTable' not found when refreshing migrations 

### ISSUE THREAD

**Issue by dambridge** [anlutro/laravel-settings#35]
`php artisan migrate:refresh --seed`

produces

`Class 'CreateSettingsTable' not found`

**Comment by dambridge** [comment]
I suspect because the migration table assumes migration is in database/migrations folder?

**Comment by anlutro** [comment]
That's correct - I would recommend you "publish" the migration (I think the command is `php artisan migrate:publish` in 4.x).

I **could** add an autoloader for the package migration, but that could cause conflicts with user-defined migrations.

**Comment by jamestowers** [comment]
`php artisan vendor:publish` in L5 ? I'm not getting anything related to laravel-settings being published after running that, bit stuck now as I can't refresh the db, any suggestions?

**Comment by anlutro** [comment]
Should work in 0.4.3.

**Comment by anlutro** [comment]
I mean 0.4.5

**Comment by jamestowers** [comment]
Ah yes 0.4.5 publishes the migration but I'm still getting `Class 'CreateSettingsTable'` not found on `migrate:refresh` / `migrate:reset`

**Comment by anlutro** [comment]
Try a `composer dump`.

**Comment by jamestowers** [comment]
Oh yeah... Thanks, that did it!

**Comment by dbhynds** [comment]
Thank you! I had the same problem.
