### ISSUE TITLE
Calling statically not working in Laravel 5

### ISSUE THREAD

**Issue by ecomus** [anlutro/laravel-settings#37]
When I try and call statically I get the error:

```
Non-static method anlutro\LaravelSettings\SettingStore::set() should not be called statically, assuming $this from incompatible context
```

This is what I'm trying:
```
use anlutro\LaravelSettings\DatabaseSettingStore as Setting;
```
```
		Setting::set('foo', 'bar');
		Setting::get('foo', 'default value');
		Setting::save();
```

I can get this working but only by using the following:
```
use anlutro\LaravelSettings\DatabaseSettingStore as Setting;
```
```
		$conn = DB::connection('database_connection');
		$store = new Setting($conn,'settings');
		$store->set('foo', 'bar');
		$store->set('nest.one', 'nestone');
		$store->set('nest.two', 'nesttwo');
		$store->set('array', array('one', 'two'));
		$store->save();
```

I'm a newbee to laravel so any help is really grateful

**Comment by bweston92** [comment]
I think you should take a look at Laravel's facade documentation. I'm in phone so no time to explain.



—

**Comment by anlutro** [comment]
Follow the instructions here: https://github.com/anlutro/laravel-settings#installation Step 2 and 4 in particular.

You're supposed to call the facade class, not the store class itself.

**Comment by ecomus** [comment]
ah ha, cool thank you for the information on the facade, I hadn't read that before.

I was looking in the database table but hadn't set it up in the settings.php file. Working now thank you both. 

Live and learn
