### ISSUE TITLE
Class not found FatalErrorException

### ISSUE THREAD

**Issue by bsh314** [anlutro/laravel-settings#38]
So one of my laravel 5.0.34 projects needs this utility. Installed it throw composer 
```php
composer require anlutro/l4-settings

// this adds 'anlutro/l4-settings": "^0.4.5' to composer.json
```
Added Service Provider & Facade 
```php
'providers' => [
    .
    .
   'anlutro\LaravelSettings\ServiceProvider',


'aliases' => [
    .
    .
    'Setting' 	=> 'anlutro\LaravelSettings\Facade'
```
All exactly as always and according to README. But my controller goes throw FatalErrorException while trying to use 'Setting' facade.

```php
use Illuminate\Http\Request;
use Artisan;
use Input;

class ConfigController extends Controller {
.
.
.
    public function config(){
        $server = Setting::get('server', 1);    <<<<<<<<   Class 'XXXXX\Http\Controllers\Setting' not found
        $count = Setting::get('count', 1000);
        return view('config')->with(compact('server','count'));
    }
```
What can it be? Trully rare problem (maybe stupid, but rare)

**Comment by bsh314** [comment]
```php
use anlutro\LaravelSettings\Facade as Setting;
```
**IS a solution**, urgly one, but works.

**Comment by anlutro** [comment]
If your controller is in a namespace, you have to `use Setting` - just like you're already doing `use Artisan` and `use Input`.

**Comment by alexchitoraga** [comment]
Use can use Setting facase as \Setting:: ....
