### ISSUE TITLE
Saving array, object to 1 key (1 record)

### ISSUE THREAD

**Issue by vuongdinhngoc** [anlutro/laravel-settings#41]
Thanks for your great package!
It would be nice if your package gave an option of saving array, object (after serialize()) to 1 key, like wordpress option.

**Comment by bweston92** [comment]
Objects aren't supported. Everything is a native value as we use json_encode. (int/float/string/array). Feel free to extend a setting store and using serialize, except it won't be compatible with any other programming language.

**Comment by anlutro** [comment]
I definitely wouldn't want to implement anything using `serialize()`, though JSON might be an option. However, I don't see a strong argument for why you'd want to do that over using one table row for each setting value - could you elaborate on why you'd like this feature?
