### ISSUE TITLE
Persistent

### ISSUE THREAD

**Issue by andrewtweber** [anlutro/laravel-settings#42]
"Persistent" is the correct spelling. "Persistant" is used in the package description, readme, etc.

**Comment by thijsdemaa** [comment]
+1

**Comment by anlutro** [comment]
How embarassing! Thanks!

**Comment by andrewtweber** [comment]
You're welcome. Don't forget this spot:

![screenshot](https://cloud.githubusercontent.com/assets/2760420/12855696/7ec39b86-cc06-11e5-9f2e-de9a1a8e69a5.png)

**Comment by anlutro** [comment]
I don't know why that didn't show up when grepping!
