### ISSUE TITLE
Laravel 5.2 compatibility problem

### ISSUE THREAD

**Issue by mspiderv** [anlutro/laravel-settings#43]
`FatalErrorException in SaveMiddleware.php line 18:
Interface 'Illuminate\Contracts\Routing\TerminableMiddleware' not found
in SaveMiddleware.php line 18`

I think class SaveMiddleware does not need to implement TerminableMiddleware interface anymore.

**Comment by anlutro** [comment]
God dammit... If I don't implement the interface, the package breaks for 5.1 and lower.

**Comment by anlutro** [comment]
https://laravel.com/docs/5.2/upgrade

> In addition, the TerminableMiddleware contract has also been deprecated.

I don't think these people know what "deprecate" means?!

**Comment by mspiderv** [comment]
What about create special "SaveMiddleware" for Laravel 5.2 or higher ? Laravel 5.1 (or older) users will still use the old "SaveMiddleware" and Laravel 5.2 (or newer) will use the new class.

**Comment by anlutro** [comment]
Yeah... I'm just getting tired of having to implement these sorts of hacks every time there's a new version that breaks backwards compatibilities for no reason whatsoever.
