### ISSUE TITLE
Json pretty print

### ISSUE THREAD

**Issue by tikhanovichA** [anlutro/laravel-settings#44]
add pls JSON_PRETTY_PRINT for JsonSettingStore:write(). This will be very helpfull, i gues :)

**Comment by anlutro** [comment]
Good idea. Would you like to try making a pull request for it? I think adding a `$jsonOptions` constructor argument to `JsonSettingStore` which is then passed on to `json_encode`/`json_decode` would be the way to go.

**Comment by bweston92** [comment]
@anlutro a PR was made for this issue by my self but ended up being closed due to inactivity. Should we reopen the PR or close this issue?

**Comment by anlutro** [comment]
I think it's a good suggestion, so definitely go for it if you have the time!

**Comment by bweston92** [comment]
@anlutro I submitted a PR for it ages ago, you didn't get round to testing/merging #49

**Comment by anlutro** [comment]
Sorry about that. I don't do any manual testing and simply didn't merge because of the 5.3 compat. This is not something I care about anymore, so if you want to re-open and just increase the version constraints in `composer.json` and `.travis.yml` I'm not going to stop you :)
