### ISSUE TITLE
How to setup a view to edit all settings in view

### ISSUE THREAD

**Issue by C0deS1ayer** [anlutro/laravel-settings#46]
I am trying to impliment this for an page that will allow the user in the admin section to set the colors. 

The actual layout I have in settings.index.blade.php is: 

```
<?php
@extends('layouts.admin')

@section('header')
    <h2>
        {!! link_to_route('admin.index','back',[],['class'=>'btn btn-default']) !!}
    </h2>
@stop

@section('panel-heading')

    <h3>Change you colors:</h3>

@stop

@section('content')

    {!! Form::open(['route'=>['admin.settings.update',$settings], 'method'=>'PUT', 'class'=>'form']) !!}


    <div class="form-group">

        {!! Form::label('background_color','Background Color') !!}

        {!! Form::text('background_color',Setting::get('background_color'),['class' => 'form-control'] ) !!}


    </div>

    <!-- Submit Button -->
    <div class="form-group">

        {!! Form::submit('Update',['class'=> 'btn btn-primary form-control']) !!}

    </div>
    {!! Form::close() !!}

@stop ?>
```

The controller I have is:

```
	public function index()
	{

          $settings = Settings::all();

		return view('admin.settings.index')->with('settings',$settings);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($settings)
	{
		echo $settings['background_color'];
		Setting::set('background_color', '#000');

		return redirect('admin');

	}
```

The seed that I am using is: 

```
<?php 
class SettingsSeeder extends Seeder {

	public function run()
	{
		DB::table('settings')->delete();


		DB::table('settings')->insert([
			[
				'key' => 'background_color',
				'value' => '#fff',
			]
		]);

	}
} ?>
```

My goal is to have all settings in the view to be updated the site.  What am I doing incorrectly?  I'm able to get the #fff into admin view but I am unable to pass the new value into the controller to be updated in the setting.  I tried using `Setting::set('background_color', '#000');`.  I would like to do this for all of the settings I have stored in the database.  Any guidance would be great.

**Comment by anlutro** [comment]
You might need to call `Settings::save()` in your `update` method, since people have reported the middleware etc. not working in Laravel 5.

**Comment by C0deS1ayer** [comment]
Do you think since I'm doing it edit on index it might not be passing the information to the update?  Is there something to do with edit that will allow it?  I added the Save:setttings and got a 500.  The next step I did was trying to var_dump out the settings request. See screen shots.  I really appreciate your help.

<img width="1310" alt="screen shot 2016-04-10 at 1 24 37 pm" src="https://cloud.githubusercontent.com/assets/787437/14412085/c52d8dd8-ff1f-11e5-861a-480fd1844620.png">

<img width="892" alt="screen shot 2016-04-10 at 1 24 47 pm" src="https://cloud.githubusercontent.com/assets/787437/14412086/c52ef1aa-ff1f-11e5-841a-b4398034fd65.png">

**Comment by C0deS1ayer** [comment]
I was able to see my error but am getting this in when clicking update.  I wasn't receiving the request before.

<img width="1092" alt="screen shot 2016-04-10 at 2 40 22 pm" src="https://cloud.githubusercontent.com/assets/787437/14412529/36e50a1e-ff2a-11e5-90d1-9389023925c8.png">

Current Update is

`	public function update(Request $request)
	{

		$background_color = $request->input('background_color');
		Settings::set('background_color', $background_color);

		return redirect('admin');

	}`

**Comment by ConquestMedia** [comment]
@C0deS1ayer were you able to fix it? I would love to know this, I am falling in something very similar

thanks

**Comment by anlutro** [comment]
Sorry for not responding here but I really can't take the time to debug basic issues for you. Your error message makes it sound like you've got the facade wrongly set up. This is all you should need in your controllers:

```php
public function edit()
{
	return View::make('admin.settings', [
		'settings' => Setting::all(),
	]);
}

public function update(Request $request)
{
	Setting::set($request->only('background_color', 'text_color'));
	Setting::save(); // not needed if you use the middleware
	return Redirect::route('admin.settings.edit')
		->with('message', 'Settings updated!');
}
```
