### ISSUE TITLE
Multiple settings per user

### ISSUE THREAD

**Issue by zaffar-saffee** [anlutro/laravel-settings#47]
say, my user has 10 different settings, should I add 10 more columns ( as example given in your repo)?

**Comment by zaffar-saffee** [comment]
Alternatively, I do keep doing set('key', value) and when I do selectAll(); it will return all settings related to that user ID?

**Comment by anlutro** [comment]
You don't need to add columns based on how many settings you have, we use an EAV system like this: https://github.com/anlutro/laravel-settings/blob/master/src/migrations/2015_08_25_172600_create_settings_table.php#L26-L31

You'd add 1 extra column to store the user ID. If you do what's shown in the readme:

```php
Setting::setExtraColumns(array(
    'user_id' => Auth::user()->id
));
```

Then all subsequent `Setting::get` calls will only fetch settings for the logged in user.

**Comment by ConquestMedia** [comment]
in my app, I need setting likes this

```
user1array[
s1; v1
s2:v2
s3:v3
],
user2array[
s1; v1
s2:v2
s3:v3
],
```

can I achieve this with single fetch? or I need to get(s1), get(2) and get(3) individually? or settingAll() will fetch this?
One more question, I can use `Setting facade` to access it, but can I add the returned settings and merge it to `Config facade`? Point is, I am using an open source library, and I don't want to edit the code... was looking for such an option  if possible...willing to fork and do the change if you can provide me some guidelines..
Library in question is [here](https://github.com/przemekperon/amazon-mws-laravel)

**Comment by anlutro** [comment]
I think you'd have to make a manual database query to get all user's settings in an array like that.

To put the settings into the config would just be a matter of `Config::set('settings', Setting::all())`

**Comment by ConquestMedia** [comment]
thanks a million....that makes more sense...forking your repo to update my required changes..and marking this issue close..
I am really thankful to you for such a great project and being such an nice man to spare your time to reply my question..

Happy Open source...keep pouring your abilities for others
God Bless you bro
