### ISSUE TITLE
[Laravel 4.2] Not getting the correct setting for individual user

### ISSUE THREAD

**Issue by 2eddy** [anlutro/laravel-settings#51]
Hi, thank you for this amazing package.

I have 1 problem though. Even though I have setExtraColumns, I am not getting the correct value from setting for each user with `Setting::all()`

What could be the reason?

I'm using Cartalyst/Sentry for authentication. Thank you for your help.

**Comment by anlutro** [comment]
I don't think sentry has anything to do with it. When and how are you calling `setExtraColumns`?

**Comment by 2eddy** [comment]
Hi anlutro,

I realized I have to place the setExtraColumns into service provider.

I have gotten this error "Illegal offset type in isset or empty" when I use this provider.

```
<?php namespace app\providers;

use Cartalyst\Sentry\Facades\Laravel\Sentry;
use Illuminate\Support\ServiceProvider;

class SettingsServiceProvider extends ServiceProvider {

    public function boot()
    {
        \Setting::setExtraColumns([
            'user_id' => Sentry::getUser()->id
        ]);
    }

    public function register()
    {
        //
    }

}
```
Is there any step which I have missed?

**Comment by anlutro** [comment]
Can you provide the full stacktrace?

**Comment by 2eddy** [comment]
Will this do?

![stacktrace](https://cloud.githubusercontent.com/assets/4593183/15092858/aeb17c24-14a8-11e6-9f26-c2754ced808c.png)

**Comment by anlutro** [comment]
Can you check what `Config::get('anlutro/l4-settings::store')` is?

**Comment by 2eddy** [comment]
It returns an empty array.

This is the content under app/config/packages/anlutro/l4-settings/config.php

`<?php
return array(
	// which type of store to use.
	// valid options: 'json', 'database'
	'store' => 'database',

	// if the json store is used, give the full path to the .json file
	// that the store writes to.
	'path' => storage_path().'/settings.json',

	// if the database store is used, set the name of the table used..
	'table' => 'settings',

	// If the database store is used, you can set which connection to use. if
	// set to null, the default connection will be used.
	'connection' => null,
);`

**Comment by anlutro** [comment]
It shouldn't return an empty array. I can't tell you why, though. Check that the configuration is in the right place, that you added the service provider etc.
