### ISSUE TITLE
provider setting on laravel 5.3

### ISSUE THREAD

**Issue by getcrud** [anlutro/laravel-settings#60]
if set provider with
`anlutro\LaravelSettings\ServiceProvider` after command php artisan vendor:publish

i found message  **Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Undefined constant 'anlutro\LaravelSettings\ServiceProvider'**

and i try with `anlutro\LaravelSettings\ServiceProvider::class` 

okey. i can publish now.

**Comment by anlutro** [comment]
Sorry, but I don't understand the problem you're having. You mention php 5.3 in the subject but `anlutro\LaravelSettings\ServiceProvider::class` was only added in php 5.5. It sounds like you just didn't add quotes around the class name the first time around.
