### ISSUE TITLE
preload basic settings

### ISSUE THREAD

**Issue by alblez** [anlutro/laravel-settings#61]
Hi Andreas,
Thank you for implementing this good idea, I'm trying to figure out the best way to preload the basic settings on the app, for example; Seeds. Have you suggestions?

Best!

**Comment by bweston92** [comment]
@alblez nothing stops you using a database seed class to seed settings.

**Comment by anlutro** [comment]
Yeah, I'm inclined to say that writing your own seeder for this is a good solution.

While seeders were originally intended to work with the database, there's no reason you can't do `file_put_contents('/path/to/settings.json', json_encode($data))` in them if you use the JSON settings store driver.
