### ISSUE TITLE
setExtraColumns

### ISSUE THREAD

**Issue by notflip** [anlutro/laravel-settings#63]
Where do you suggest adding the following line? 
Can it also be added in a Controller so we can add id's of other entites then the user

Setting::setExtraColumns(array(
    'user_id' => Auth::user()->id
));

**Comment by anlutro** [comment]
Unfortunately I'm not really familiar with Laravel 5 so I'm not sure what the correct place to put it would be. Maybe [a service provider's boot method](https://github.com/laravel/laravel/blob/c76716f228d809d24d1886c3e279d08fb8377ebc/app/Providers/AppServiceProvider.php#L16)?

It obviously has to be at a point where `Auth::user()` returns the logged in user, but before any other `Setting::` calls are made. Putting it in the controller is fine as long as you only ever use `Setting::` calls in that controller, but that's probably not what you want.

**Comment by bweston92** [comment]
The correct place IMO would be in the middleware stack or in a service provider.

This can be closed as it was more of a request for guidance.

**Comment by anlutro** [comment]
Alright. Maybe something could be added to the readme on this subject, but I'm not sure exactly how to formulate it.
