### ISSUE TITLE
Problem with reserved word in oracle

### ISSUE THREAD

**Issue by andreslancheros** [anlutro/laravel-settings#65]
I have a problem when try to save a setting using oracle, because the table column is called "key" which is a Oracle reserved word. It's possible in some way set a custom name for package table columns?

**Comment by anlutro** [comment]
That's not currently possible, but shouldn't be too hard to implement if you want to try and make a pull request.

**Comment by andreslancheros** [comment]
Ok, thanks, I'll try to do that.

**Comment by anlutro** [comment]
Awesome. Let me know if you would like some hints or guidance!

**Comment by andreslancheros** [comment]
Thank your for your answer, this is the first time I'm collaborating on github project, and I'm not sure how to do it. I already did the change, and push it into a forked repository (https://github.com/andreslancheros/laravel-settings).
I want to know if I can do the pull request into this repository, or if you could check the changes first on my forked repository, to help me with some feedback?
Thanks again.

**Comment by anlutro** [comment]
No problem, I'm more than happy to introduce you to how it works :)

Just do the pull request and I'll give feedback there. If you go here: https://github.com/andreslancheros/laravel-settings/tree/database-columns-name-param-to-avoid-conflict-with-oracle-reserved-words

There should be a "new pull request" button somewhere on the left, next to the dropdown where you select a branch.

**Comment by bweston92** [comment]
Just created the PR on your behalf @andreslancheros - hopefully @anlutro can take a look at it soon enough.

**Comment by codetheorist** [comment]
I'd say it makes perfect sense to have table and column names in the config file, but maybe another issue needs to be created for implementing migration publishing.

All of the official Laravel packages have table and column names in the config file, as well as other popular 3rd party packages, such as [Spatie's Laravel Permissions](https://github.com/spatie/laravel-permission) or [Marcel Pociot's Teamwork](https://github.com/mpociot/teamwork).
