### ISSUE TITLE
FatalErrorException in Manager.php line 138: Call to undefined method anlutro\LaravelSettings\JsonSettingStore::setExtraColumns()

### ISSUE THREAD

**Issue by mitto98** [anlutro/laravel-settings#67]
I'm getting this error when I try to set an extra column in laravel 5.4.16

![7a85458993c6a62efaf80a3dd858eb50](https://cloud.githubusercontent.com/assets/10376295/24588579/2ddad4de-17cb-11e7-8ae0-ebeac36c89d9.png)

I've added the provider to the provider list and done the migration and i'm using a middleware to handle the command.

```
namespace App\Http\Middleware;

use Closure;
use anlutro\LaravelSettings\Facade as SettingsFacade;
use Illuminate\Support\Facades\Auth;

class Settings
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Closure $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        SettingsFacade::setExtraColumns([
            'autoscuola_id' => Auth::user()->autoscuola->id
        ]);
        return $next($request);
    }
}
```

**Comment by shadywallas** [comment]
setExtra Columns is available for database store , what is the use case here , why do you need this implementation, 

publish configuration, then change config/setting.php 

set store to database  instead of json , also a proper handle should be done to this issue

**Comment by mitto98** [comment]
Thank you! Now it works
