### ISSUE TITLE
Store on different connection not work

### ISSUE THREAD

**Issue by abkrim** [anlutro/laravel-settings#69]
Steps

1. config database.php for sqlite connection
2. config settings.php for use store on database,  path,...

```
'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'database' => database_path('config.sqlite'),
            'prefix' => '',
        ],
```

```
return array(
	'store' => 'database',
	'path' => storage_path().'/settings.json',
	'table' => 'settings',
	'connection' => 'sqlite',
	'keyColumn' => 'key',
	'valueColumn' => 'value'
);
```

Run `php artisan migrate` or `php artisan migrate --path=vendor/anlutro/l4-settings/src/migrations` but two commands same the same problem, 

-> Create table on other connection (mysql database)

the sqlite database exists, `storage_path().'/settings.json'`

```
ls -lisa database/config.sqlite 
34526339 0 -rw-r--r--  1 abkrim  staff  0 Jun 10 18:25 database/config.sqlite
```

**Comment by anlutro** [comment]
Hey,

I'm not 100% sure but don't you need to pass the connection name to the migrate command? I'm not sure if this is something I can do anything about.

**Comment by abkrim** [comment]
A lot of thanks
`php artisan migrate --database='NAME_OF_CONNECTION' --path=vendor/anlutro/l4-settings/src/migrations  `
