### ISSUE TITLE
no data returned

### ISSUE THREAD

**Issue by marksie1988** [anlutro/laravel-settings#70]
Hi, i have installed this with the latest Laravel 5.4 and cant get any data back: 

config\app.php
```
PROVIDER
------------------
anlutro\LaravelSettings\ServiceProvider::class,

ALIAS
-------------------
'Setting' => anlutro\LaravelSettings\Facade::class,
```

Controller:
```
use Setting; 
class ApiController extends Controller{
public function index()
    {
        print_r(Setting::all());
      
    }
}```

the arrary is just blank even though i have added entries to the table. same happens if i use "Get"

**Comment by bweston92** [comment]
What do you have for this value?
https://github.com/anlutro/laravel-settings/blob/master/src/config/config.php#L5

**Comment by marksie1988** [comment]
Yea that was the issue! Didn't notice the config file just assumed it used the database 😬 Thanks
