### ISSUE TITLE
Laravel 5.5 autodiscovery not tagged yet  

### ISSUE THREAD

**Issue by mogahead** [anlutro/laravel-settings#78]
Laravel 5.5 autodiscovery not tagged yet , It only found on dev-master branch and not tagged tel now
plz add new tag with the latest changes @anlutro

**Comment by bweston92** [comment]
Whoops @mogahead it is now tagged at `0.5.1` https://github.com/anlutro/laravel-settings/releases/tag/0.5.1

**Comment by mogahead** [comment]
done , thanks @anlutro
