### ISSUE TITLE
v0.5.0 to 0.5.1 broke - Laravel 5.4 Migration name conflict

### ISSUE THREAD

**Issue by chadanuk** [anlutro/laravel-settings#79]
[This code in `ServiceProvider.php`](https://github.com/anlutro/laravel-settings/blob/0.5.1/src/ServiceProvider.php#L62) breaks our L5.4 app because we have the migration class already existing with the same name (as already published to `database/migrations`). 

This causes an issue where both migration classes are autoloaded so a php error is thrown.

This error can be resolved by removing our published migration, however running migrate throws a DB error because the table already exists (as the migration filename has changed).

```php
if (version_compare(Application::VERSION, '5.3', '>=')) {
    $this->loadMigrationsFrom(__DIR__.'/migrations');

    $this->publishes([
        __DIR__.'/config/config.php' => config_path('settings.php')
    ], 'config');
} 
```

Suggest the version should need to be >= than 5.5 where the autoloading is expected behaviour?
```php
if (version_compare(Application::VERSION, '5.5', '>=')) {
    $this->loadMigrationsFrom(__DIR__.'/migrations');

    $this->publishes([
        __DIR__.'/config/config.php' => config_path('settings.php')
    ], 'config');
} 
```

Alternatively, the migration could check for an existing `settings` table before creating.

```php
if(!Schema::hasTable(Config::get('settings.table')) { ...
```

**Comment by anlutro** [comment]
Urgh. Maybe just revert the change and release the auto-discovered one as 0.6.0. I have no idea what the correct approach is supposed to be.

**Comment by anlutro** [comment]
That being said, if autodiscovery breaks backwards compatibility like this, maybe it's not worth implementing at all.

**Comment by bweston92** [comment]
@chadanuk I doubled checked that the service provider can call `$this->loadMigrationsFrom` and `$this->publishes` when version 5.3 or above.

I agree with @anlutro we should make this a 0.6 release instead, unfortunately I over looked testing with existing installations whereby the migration had already occurred.

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/ServiceProvider.php#L109
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/ServiceProvider.php#L125

**Comment by chadanuk** [comment]
@bweston92 @anlutro That makes sense. 

👍

**Comment by anlutro** [comment]
Pushed 0.5.2 and 0.6.0 now, should fix the problem I guess. @bweston92 I don't think anyone can be expected to remember or know all the possible ways Laravel can break things, honestly.

**Comment by anlutro** [comment]
Pushed 0.5.2 and 0.6.0 now, should fix the problem I guess. @bweston92 I don't think anyone can be expected to remember or know all the possible ways Laravel can break things, honestly.
