### ISSUE TITLE
Add migration publishing to service provider

### ISSUE THREAD

**Issue by codetheorist** [anlutro/laravel-settings#81]
Implement the required functionality to properly publish the migration file to the sites `database/migrations` folder.

**Comment by FinesseRus** [comment]
+1. Running an individual command for an individual migration is a clutter.

**Comment by FinesseRus** [comment]
**Update.** This issue is closed via #92. Now the only thing you need is to run `php artisan vendor:publish --provider="anlutro\LaravelSettings\ServiceProvider" --tag="migrations"` to copy the migration to your migrations directory.
