### ISSUE TITLE
Configuration File

### ISSUE THREAD

**Issue by egknight** [anlutro/laravel-settings#85]
In Laravel 5.5, when I run

```php artisan vendor:publish --provider="anlutro/l4-settings" --tag="config"```

I expect a local configuration file in config/

I see a config file in vendor folder, but this folder is in my .gitignore

Running ```php artisan vendor:publish``` publishes the file as expected to config/

**Comment by anlutro** [comment]
Do you know of another package that behaves the way you'd expect?

**Comment by egknight** [comment]
Just updated comment above, running ```php artisan vendor:publish``` works as expected, however, I don't know if that has other consequences.

**Comment by anlutro** [comment]
That's weird, but I'm tempted to say this is a bug in Laravel, not with this package.

**Comment by egknight** [comment]
Ok, understood, for me the publish is not an issue. Good for other users to know in any case.

Thanks

**Comment by dejan7** [comment]
I have Laravel version 5.5.22 and neither command works for me.
Running `php artisan vendor:publish --provider="anlutro/l4-settings" --tag="config"` doesn't copy the file and running `php artisan vendor:publish` gives me a list of packages to publish from, but this package is not among them. 

Hint for other people encountering the same issue: copy `/vendor/anlutro/src/config/config.php` to `/config/settings.php`, everything appears to be functional.

**Comment by sarhugo** [comment]
FYI the error is in the provider parameter.. you must point to the class name of service provider. Correct command line is:

`php artisan vendor:publish --provider="anlutro\LaravelSettings\ServiceProvider" --tag="config"`
