### ISSUE TITLE
not publish config

### ISSUE THREAD

**Issue by vahidalvandi** [anlutro/laravel-settings#89]
i use laravel 5.5 then after run
php artisan vendor:publish --provider="anlutro/l4-settings" --tag="config"
not copy config file in config folder

thanks

**Comment by beaubuehler** [comment]
Take a look at #85.

**Comment by anlutro** [comment]
Hey, sorry for not replying.

I haven't really been involved in Laravel for 2 years now so I really don't know how the modern style vendor publishing is supposed to work. As far as I can tell I've followed the [documentation](https://laravel.com/docs/5.5/packages#publishing-file-groups), so it *should* work - if it doesn't then my best guess is a bug in Laravel, which I'm not going to investigate.

If you have more details on what's wrong in this package I'd be happy to try and fix it, until then there's not much I can/will do.

**Comment by sarhugo** [comment]
FYI the error is in the provider parameter.. you must point to the class name of service provider. Correct command line is:

`php artisan vendor:publish --provider="anlutro\LaravelSettings\ServiceProvider" --tag="config"`

**Comment by anlutro** [comment]
@sarhugo thanks for pointing that out! Would you like to make a pull request to correct this in the readme? Do you know if this affects all versions of Laravel or just a few?

**Comment by sarhugo** [comment]
@anlutro checking when provider parameter was initially implemented seems that always was the class name: https://github.com/laravel/framework/commit/160c68d05ac73d671aaf188668401c973166feea#diff-8e559dffe73d8f3f506545dd3ba6346e

I'll make a PR fixing the readme
